name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          user: Alvin187187
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Languages activity
        uses: lowlighter/metrics@latest
        with:
          user: Alvin187187
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
          plugin_languages_ignored: html, css, json, markdown, dockerfile
          plugin_languages_limit: 8
          repositories_affiliations: owner
